const Test = [
  {
    category: '러닝',
    place: '중랑구',
    date: '2024-07-03T19:00:00',
    title: '중랑천 함께 뛰어요',
    member: 20,
    imageUrl: '/images/러닝이미지.jpg',
    deadline: '오늘마감',
    confirmed: true,
    review: true,
  },
  {
    category: '축구',
    place: '송파구',
    date: '2024-07-09T11:00:00',
    title: '풋살 하실 분~',
    member: 3,
    imageUrl: '/images/풋살이미지.jpeg',
    deadline: '이번주마감',
    confirmed: false,
    review: false,
  },
  {
    category: '등산',
    place: '광진구',
    date: '2024-07-19T14:00:00',
    title: '아차산 정상까지 등산 14년차 베테랑이 함께해요 가나다',
    member: 14,
    imageUrl: '/images/등산이미지.png',
    deadline: '다음주마감',
    confirmed: true,
    review: false,
  },
];
export default Test;
